# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioWebhookMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text=b'When we received the event.')),
                ('message', jsonfield.fields.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioWebhookMessageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text=b'When we received the event.')),
                ('sms_status', models.CharField(max_length=250, null=True)),
                ('sms_sid', models.CharField(max_length=250, null=True)),
                ('account_sid', models.CharField(max_length=250, null=True)),
                ('message_sid', models.CharField(max_length=250, null=True)),
                ('election_uuid', models.CharField(max_length=250, null=True)),
                ('to_number', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='twiliowebhookmessagedetail',
            index=models.Index(fields=[b'received_at', b'election_uuid', b'to_number'], name='dj_twilio_t_receive_cbcd15_idx'),
        ),
        migrations.AddIndex(
            model_name='twiliowebhookmessage',
            index=models.Index(fields=[b'received_at'], name='dj_twilio_t_receive_6beae6_idx'),
        ),
    ]
