# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text=b'When we received the event.')),
                ('message', jsonfield.fields.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookMessageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text=b'When we received the event.')),
                ('codigosms', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=250, null=True)),
                ('election_uuid', models.CharField(max_length=250, null=True)),
                ('celular', models.CharField(max_length=250, null=True)),
                ('shortcode', models.CharField(max_length=250)),
                ('mensagem', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookmessagedetail',
            index=models.Index(fields=[b'celular', b'election_uuid', b'codigosms'], name='dj_iagentes_celular_6ff8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookmessage',
            index=models.Index(fields=[b'received_at'], name='dj_iagentes_receive_8776e5_idx'),
        ),
    ]
