# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_iagentesms', '0002_auto_20211117_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookmessagedetail',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
