# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text=b'When we received the event.')),
                ('message', jsonfield.fields.JSONField(default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookmessage',
            index=models.Index(fields=[b'received_at'], name='dj_sendgrid_receive_3e6c37_idx'),
        ),
    ]
