# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sendgrid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookMessageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text=b'When we received the event.')),
                ('event_name', models.CharField(default=b'bounce', max_length=250)),
                ('type', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(max_length=250, null=True)),
                ('server', models.CharField(max_length=250, null=True)),
                ('election_uuid', models.CharField(max_length=250, null=True)),
                ('email_from', models.CharField(max_length=250, null=True)),
                ('email_to', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookmessagedetail',
            index=models.Index(fields=[b'received_at', b'election_uuid', b'email_to'], name='dj_sendgrid_receive_5ab5fb_idx'),
        ),
    ]
