# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_sendgrid', '0002_auto_20211110_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookmessagedetail',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
